from __future__ import annotations

PREVIEW_TEXT_READ_LIMIT = 1_500_000
DUPLICATION_WINDOW_SIZE = 6
DUPLICATION_MAX_WINDOWS_PER_FILE = 200
MAX_FILE_SCAN_BYTES = 2_000_000
DEFAULT_RECENT_COMMITS = 8
DEFAULT_CHURN_LOG_LIMIT = 250
